### ISSUE TITLE
Pruning YOLOv4 (from darknet)

### ISSUE THREAD

**Issue by jeffreylowzg** [pedbrgs/Pruning-Darknet#1]
Hi, 

I attempted to prune the pretrained YOLOv4 from darknet but I faced some issues. 

Using your guide, I have installed and am able to generate the pruned models. By running prune.py with the darknet pre-trained yolov4.cfg and yolov4.weights, I was able to generate a pruned model in /darknet/temp/. 

However, using ./darknet detect with these pruned cfg and weights gave me the following results. Is there anything wrong with my implementation? Thank you! 

##the predictions.jpg are the same for all 3 methods.

![predictions - dog](https://user-images.githubusercontent.com/52026975/218681941-6a5ea058-8209-4f9b-8e23-b349ad5144e6.jpg)

![predictions - horses](https://user-images.githubusercontent.com/52026975/218681931-ca1e447a-f416-435d-9db9-6591b24d581f.jpg)

**Comment by pedbrgs** [comment]
Hi @jeffreylowzg! 

Thank you for your interest in my work.

Did you fine-tuning the network after pruning? This is an important step. After pruning p% of filters in all prunable layers of the network, the remaining filters can present an undesirable behavior, since their contribution to the output can be highly correlated with some filter that was removed. Therefore, it is advisable to readjust the remaining parameters through fine-tuning. For that purpose, just train the network for a few more iterations (e.g., 10,000) and try the prediction again.

**Comment by jeffreylowzg** [comment]
Hey @pedbrgs 

Thank you for the amazing work! 

I think you were right in my implementation not doing the fine-tuning properly. I have been trying to pinpoint the issue (could be training image error or GPU memory issues, darknet training stops randomly). I will update this thread should I have any headway in this! Thank you!

**Comment by dangtuan18** [comment]
Hello @pedbrgs, thank you for the great work. My network size is not square, it is 640x480, how can I use your code?

**Comment by pedbrgs** [comment]
Hi @tuanmonkeyy!

Thank you for your interest in my work. 

Currently, there is no ready-made way to do this. But you can change a few lines of code to prune YOLOv4 networks with non-square inputs. It is not complicated.

Note that the [Darknet class](https://github.com/pedbrgs/Pruning-Darknet/blob/87ec1a680dd0fffa12cd7d7ba5097d35b3916b37/models.py#L220) already accepts a tuple as a `img_size` parameter. By the way, the default value is `(416, 416)`. However, the [YOLO function](https://github.com/pedbrgs/Pruning-Darknet/blob/87ec1a680dd0fffa12cd7d7ba5097d35b3916b37/utils/build.py#L7) instantiates an object of the Darknet class passing a single value for the image size. It is in calling this function in [prune.py](https://github.com/pedbrgs/Pruning-Darknet/blob/main/prune.py#L54) that you must change the code.

If you are going to use projection-based methods, which I do not suggest for this case, then you will have to change more lines of code. Starting with the [get_variables function](https://github.com/pedbrgs/Pruning-Darknet/blob/87ec1a680dd0fffa12cd7d7ba5097d35b3916b37/pruning/techniques.py#L958).

**Comment by tuanmonkeyy** [comment]
> Hi @tuanmonkeyy!
> 
> Thank you for your interest in my work.
> 
> Currently, there is no ready-made way to do this. But you can change a few lines of code to prune YOLOv4 networks with non-square inputs. It is not complicated.
> 
> Note that the [Darknet class](https://github.com/pedbrgs/Pruning-Darknet/blob/87ec1a680dd0fffa12cd7d7ba5097d35b3916b37/models.py#L220) already accepts a tuple as a `img_size` parameter. By the way, the default value is `(416, 416)`. However, the [YOLO function](https://github.com/pedbrgs/Pruning-Darknet/blob/87ec1a680dd0fffa12cd7d7ba5097d35b3916b37/utils/build.py#L7) instantiates an object of the Darknet class passing a single value for the image size. It is in calling this function in [prune.py](https://github.com/pedbrgs/Pruning-Darknet/blob/main/prune.py#L54) that you must change the code.
> 
> If you are going to use projection-based methods, which I do not suggest for this case, then you will have to change more lines of code. Starting with the [get_variables function](https://github.com/pedbrgs/Pruning-Darknet/blob/87ec1a680dd0fffa12cd7d7ba5097d35b3916b37/pruning/techniques.py#L958).
Thanks, I successfully pruned my YOLOv4 model with your L1 technique, 0.6 pruning rate and get very good result. I'm deploying it on FPGA ZCU104, I will cite your paper.

**Comment by dangtuan18** [comment]
Thank you @pedbrgs, I successfully pruned my YOLOv4 model with your L1 technique, 0.6 pruning rate and get very good result. I'm deploying it on FPGA ZCU104, I will cite your paper, did you also use L1-norm pruning?

**Comment by pedbrgs** [comment]
Great, @tuanmonkeyy! Glad to know that my tool was useful for your work.

In fact, in my paper I investigated all the techniques implemented here. However, the best results in my application were obtained with techniques based on norms (L1 and L2). You did well to try L1-norm first.
