### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'temp/classes.cfg'

### ISSUE THREAD

**Issue by asyura77** [pedbrgs/Pruning-Darknet#2]
Hi,
I am having this error when trying to prune my project.

![image](https://user-images.githubusercontent.com/129488186/229042922-61b2e154-f558-4143-aad5-cf61c9acfd16.png)

can you advice?

Thank you

**Comment by pedbrgs** [comment]
Hi @asyura77,

Thank you for your interest in my work!

This looks like directory path error to me. Did you follow the tutorial? Make sure that you have moved the files from this repository to the root of the Darknet repository.
